# Generated by Django 2.2.5 on 2020-10-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='image',
            field=models.FileField(upload_to='lectura', verbose_name='PDF'),
        ),
    ]
